In [113]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [114]:
import pandas as pd
import datetime as datetime
import numpy as np
import matplotlib.pyplot as plt
filet = r"/content/drive/MyDrive/Proyecto final/healthcare_dataset.csv"

In [115]:
base=pd.read_csv(filet)

In [116]:
base

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [117]:
base.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [119]:
base.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [120]:
print(base.duplicated().sum())

534

In [121]:
base.drop_duplicates(inplace=True)

In [122]:
base

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [123]:
base["Name"]=base["Name"].str.title()

In [124]:
base["Date of Admission"]=pd.to_datetime(base['Date of Admission'])
base["Discharge Date"]=pd.to_datetime(base['Discharge Date'])
base['Billing Amount']=base['Billing Amount'].astype(int)

In [125]:
base

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [126]:
base.drop(["Insurance Provider","Billing Amount","Blood Type"],axis=1, inplace=True)

In [127]:
base

,Name,Age,Gender,Medical Condition,Date of Admission,Doctor,Hospital,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby Jackson,30,Male,Cancer,2024-01-31,Matthew Smith,Sons and Miller,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie Terry,62,Male,Obesity,2019-08-20,Samantha Davies,Kim Inc,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny Smith,76,Female,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew Watts,28,Female,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43,Female,Cancer,2022-09-19,Kathleen Hanna,White-White,458,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,417,Elective,2020-09-15,Penicillin,Abnormal
55496,Kyle Perez,61,Female,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,316,Elective,2020-02-01,Aspirin,Normal
55497,Heather Wang,38,Female,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,Jennifer Jones,43,Male,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,James Garcia,53,Female,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [133]:
base['Days Hospitalized'] = (base['Discharge Date'] - base['Date of Admission']).dt.days
base

,Name,Age,Gender,Medical Condition,Date of Admission,Doctor,Hospital,Room Number,Admission Type,Discharge Date,Medication,Test Results,Days Hospitalized
0,Bobby Jackson,30,Male,Cancer,2024-01-31,Matthew Smith,Sons and Miller,328,Urgent,2024-02-02,Paracetamol,Normal,2
1,Leslie Terry,62,Male,Obesity,2019-08-20,Samantha Davies,Kim Inc,265,Emergency,2019-08-26,Ibuprofen,Inconclusive,6
2,Danny Smith,76,Female,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,205,Emergency,2022-10-07,Aspirin,Normal,15
3,Andrew Watts,28,Female,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",450,Elective,2020-12-18,Ibuprofen,Abnormal,30
4,Adrienne Bell,43,Female,Cancer,2022-09-19,Kathleen Hanna,White-White,458,Urgent,2022-10-09,Penicillin,Abnormal,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
55495,Elizabeth Jackson,42,Female,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,417,Elective,2020-09-15,Penicillin,Abnormal,30
55496,Kyle Perez,61,Female,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,316,Elective,2020-02-01,Aspirin,Normal,9
55497,Heather Wang,38,Female,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",347,Urgent,2020-08-10,Ibuprofen,Abnormal,28
55498,Jennifer Jones,43,Male,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",321,Elective,2019-05-31,Ibuprofen,Abnormal,6
55499,James Garcia,53,Female,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,448,Urgent,2024-04-29,Ibuprofen,Abnormal,27